#pragma once
// Define a custom message ID
#define WM_USER_TOOL (WM_USER + 1000)

//draw
#define WM_USER_A_CREATELINE (WM_USER_TOOL + 1001)
#define WM_USER_A_CREATECIRCLE (WM_USER_TOOL + 1002)
#define WM_USER_A_CREATERECTANGLE (WM_USER_TOOL + 1003)
#define WM_USER_A_CREATERTEXT (WM_USER_TOOL + 1004)
#define WM_USER_A_CREATEPOLYLINE (WM_USER_TOOL + 1005)
#define WM_USER_A_CREATEELLIPSE (WM_USER_TOOL + 1006)
#define WM_USER_A_CREATESPLINE (WM_USER_TOOL + 1007)
#define WM_USER_A_CREATEARC (WM_USER_TOOL + 1008)
#define WM_USER_A_CREATEHATCH (WM_USER_TOOL + 1009)
#define WM_USER_A_CREATEMTEXT (WM_USER_TOOL + 1010)

//annotation
#define WM_USER_TOOL_ANNOTATION (WM_USER + 1500)
#define WM_USER_A_CREATE_DIM_LINEAR (WM_USER_TOOL_ANNOTATION + 1001)
#define WM_USER_A_CREATE_DIM_ALIGNED (WM_USER_TOOL_ANNOTATION + 1002)
#define WM_USER_A_CREATE_DIM_ANGULAR (WM_USER_TOOL_ANNOTATION + 1003)
#define WM_USER_A_CREATE_DIM_RADIUS (WM_USER_TOOL_ANNOTATION + 1004)
#define WM_USER_A_CREATE_LEADER (WM_USER_TOOL_ANNOTATION + 1005)

//entity
#define WM_USER_TOOL_ENTITY (WM_USER + 1100)
#define WM_USER_A_DELETEENTITIES (WM_USER_TOOL_ENTITY + 1001)
#define WM_USER_A_LISTENTITIES (WM_USER_TOOL_ENTITY + 1002)
#define WM_USER_A_ENTITYCOPY (WM_USER_TOOL_ENTITY + 1003)
#define WM_USER_A_ENTITYMOVE (WM_USER_TOOL_ENTITY + 1004)
#define WM_USER_A_ENTITYROTATE (WM_USER_TOOL_ENTITY + 1005)
#define WM_USER_A_ENTITYSCALE (WM_USER_TOOL_ENTITY + 1006)
#define WM_USER_A_ENTITYMIRROR (WM_USER_TOOL_ENTITY + 1007)
#define WM_USER_A_ENTITYOFFSET (WM_USER_TOOL_ENTITY + 1008)
#define WM_USER_A_ENTITYFILLET (WM_USER_TOOL_ENTITY + 1009)
#define WM_USER_A_ENTITYCHAMFER (WM_USER_TOOL_ENTITY + 1010)
#define WM_USER_A_ENTITYARRAY (WM_USER_TOOL_ENTITY + 1011)
#define WM_USER_A_ENTITYGET (WM_USER_TOOL_ENTITY + 1012)
#define WM_USER_A_ENTITYSETCOLOR (WM_USER_TOOL_ENTITY + 1013)
#define WM_USER_A_ENTITYGETSELECTION (WM_USER_TOOL_ENTITY + 1014)
#define WM_USER_A_ENTITYSETSELECTION (WM_USER_TOOL_ENTITY + 1015)

//layer
#define WM_USER_TOOL_LAYER (WM_USER + 1200)
#define WM_USER_A_CREATELAYER (WM_USER_TOOL_LAYER + 1001)
#define WM_USER_A_LISTLAYERS (WM_USER_TOOL_LAYER + 1002)
#define WM_USER_A_QUERYLAYER (WM_USER_TOOL_LAYER + 1003)
#define WM_USER_A_GETCURRENTLAYER (WM_USER_TOOL_LAYER + 1004)
#define WM_USER_A_SETCURRENTLAYER (WM_USER_TOOL_LAYER + 1005)
#define WM_USER_A_GETCURRENTLAYERCOLOR (WM_USER_TOOL_LAYER + 1006)
#define WM_USER_A_QUERYALLLAYERS (WM_USER_TOOL_LAYER + 1007)
#define WM_USER_A_LAYERSETPROPERTIES (WM_USER_TOOL_LAYER + 1008)
#define WM_USER_A_LAYERFREEZE (WM_USER_TOOL_LAYER + 1009)
#define WM_USER_A_LAYERTHAW (WM_USER_TOOL_LAYER + 1010)
#define WM_USER_A_LAYERLOCK (WM_USER_TOOL_LAYER + 1011)
#define WM_USER_A_LAYERUNLOCK (WM_USER_TOOL_LAYER + 1012)

//block
#define WM_USER_TOOL_BLOCK (WM_USER + 1300)
#define WM_USER_A_BLOCKLIST (WM_USER_TOOL_BLOCK + 1001)
#define WM_USER_A_BLOCKINSERT (WM_USER_TOOL_BLOCK + 1002)
#define WM_USER_A_BLOCKINSERTWITHATTRS (WM_USER_TOOL_BLOCK + 1003)
#define WM_USER_A_BLOCKGETATTRS (WM_USER_TOOL_BLOCK + 1004)
#define WM_USER_A_BLOCKUPDATEATTRS (WM_USER_TOOL_BLOCK + 1005)
#define WM_USER_A_BLOCKDEFINE (WM_USER_TOOL_BLOCK + 1006)

//view
#define WM_USER_TOOL_VIEW (WM_USER + 1600)
#define WM_USER_A_ZOOM_EXTENTS (WM_USER_TOOL_VIEW + 1001)
#define WM_USER_A_ZOOM_WINDOW (WM_USER_TOOL_VIEW + 1002)
#define WM_USER_A_GET_SCREENSHOT (WM_USER_TOOL_VIEW + 1003)

//style
#define WM_USER_TOOL_STYLE (WM_USER + 1700)
#define WM_USER_A_ADD_TEXT_STYLE (WM_USER_TOOL_STYLE + 1001)
#define WM_USER_A_MODIFY_TEXT_STYLE (WM_USER_TOOL_STYLE + 1002)
#define WM_USER_A_DELETE_TEXT_STYLE (WM_USER_TOOL_STYLE + 1003)
#define WM_USER_A_ADD_DIM_STYLE (WM_USER_TOOL_STYLE + 1004)
#define WM_USER_A_MODIFY_DIM_STYLE (WM_USER_TOOL_STYLE + 1005)
#define WM_USER_A_DELETE_DIM_STYLE (WM_USER_TOOL_STYLE + 1006)
#define WM_USER_A_LIST_TEXT_STYLES (WM_USER_TOOL_STYLE + 1007)
#define WM_USER_A_GET_TEXT_STYLES (WM_USER_TOOL_STYLE + 1008)
#define WM_USER_A_LIST_DIM_STYLES (WM_USER_TOOL_STYLE + 1009)
#define WM_USER_A_GET_DIM_STYLES (WM_USER_TOOL_STYLE + 1010)

//global
#define WM_USER_TOOL_CMD (WM_USER + 1400)
#define WM_USER_A_GETDRAWINGUNITS (WM_USER + 1401)

#define WM_USER_A_REGEN (WM_USER + 3000)
#define WM_USER_TOOL_TEST (WM_USER + 3001)

#define WM_USER_FEATURE_PLANVIEW (WM_USER + 5001)
#define WM_USER_FEATURE_COLUMNVIEW (WM_USER + 5002)
#define WM_USER_FEATURE_SECTIONVIEW (WM_USER + 5003)

#define WM_USER_CHAT (WM_USER + 4000)
#define WM_USER_CHAT_SEND_ERROR (WM_USER + 4001)

#define HOLE_DIAMETER_ZK "hole_diameter_zk"

#define MENUGROUP _T("SLTOOLS")

//#ifdef _AUTOCAD2005
typedef wchar_t KCHAR;
//#endif


struct cJSON;
// Add this struct definition in AiApiRequest.h or a common header
// In AiApiRequest.h or where the struct is defined
struct AiToolCommandData {
    cJSON* jsonRoot;      // Input JSON from HTTP request
    HANDLE hEvent;        // Sync event
	int ret;
    cJSON* resultJson;    // Output JSON result from CAD (can be NULL)
    
    // Constructor to initialize members
    AiToolCommandData() : jsonRoot(NULL), hEvent(NULL), ret(1), resultJson(NULL) {}
};


